services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    ports:
      - 24005:5244
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge
