services:
  ezbookkeeping:
    image: mayswind/ezbookkeeping:latest
    container_name: ezbookkeeping
    user: "0:0"
    ports:
      - 25005:8080
    volumes:
      - /tmp/zfsv3/sata11/13051661743/data/Docker/ezbookkeeping/storage:/ezbookkeeping/storage
      - /tmp/zfsv3/sata11/13051661743/data/Docker/ezbookkeeping/log:/ezbookkeeping/log
      - /etc/localtime:/etc/localtime:ro
    environment:
      - EBK_SERVER_ENABLE_GZIP=true
      - EBK_DATABASE_TYPE=mysql
      - EBK_DATABASE_HOST=127.0.0.1:3306
      - EBK_DATABASE_NAME=ezbookkeeping
      - EBK_DATABASE_USER=root
      - EBK_DATABASE_PASSWD=password
      - EBK_LOG_MODE=console file
      - EBK_SECURITY_SECRET_KEY=123456
    restart: always
    network_mode: ezbookkeeping
